
import { 
  UtensilsCrossed, 
  Car, 
  ShoppingBag, 
  Tv, 
  Receipt, 
  Heart, 
  TrendingUp, 
  Coffee,
  Smartphone,
  Home,
  Briefcase
} from 'lucide-react';

export const sampleUser = {
  id: 'usr_001',
  name: 'Alex Johnson',
  email: 'alex@example.com',
  defaultCurrency: 'USD',
  avatarUrl: 'https://i.pravatar.cc/150?u=usr_001'
}

export const sampleCategories = [
  { id: 'cat_001', name: 'Food & Dining', icon: UtensilsCrossed, color: '#f59e0b', type: 'EXPENSE' },
  { id: 'cat_002', name: 'Transportation', icon: Car, color: '#3b82f6', type: 'EXPENSE' },
  { id: 'cat_003', name: 'Shopping', icon: ShoppingBag, color: '#ec4899', type: 'EXPENSE' },
  { id: 'cat_004', name: 'Entertainment', icon: Tv, color: '#8b5cf6', type: 'EXPENSE' },
  { id: 'cat_005', name: 'Bills & Utilities', icon: Receipt, color: '#ef4444', type: 'EXPENSE' },
  { id: 'cat_006', name: 'Healthcare', icon: Heart, color: '#10b981', type: 'EXPENSE' },
  { id: 'cat_007', name: 'Income', icon: TrendingUp, color: '#14b8a6', type: 'INCOME' },
  { id: 'cat_008', name: 'Coffee', icon: Coffee, color: '#78350f', type: 'EXPENSE' },
  { id: 'cat_009', name: 'Electronics', icon: Smartphone, color: '#6366f1', type: 'EXPENSE' },
  { id: 'cat_010', name: 'Rent', icon: Home, color: '#4f46e5', type: 'EXPENSE' },
  { id: 'cat_011', name: 'Business', icon: Briefcase, color: '#64748b', type: 'EXPENSE' },
]

export const sampleBankAccounts = [
  {
    id: 'ba_001',
    accountName: 'Alex Johnson',
    bankName: 'Chase Bank',
    accountNumber: '****1234',
    accountType: 'checking',
    isPrimary: true,
    balance: 4129.50,
    currency: 'USD'
  },
  {
    id: 'ba_002',
    accountName: 'Savings Account',
    bankName: 'Chase Bank',
    accountNumber: '****5678',
    accountType: 'savings',
    isPrimary: false,
    balance: 12450.00,
    currency: 'USD'
  },
]

export const sampleTransactions = [
  {
    id: 'txn_001',
    amount: 42.50,
    currency: 'USD',
    transactionType: 'EXPENSE',
    transactionDate: '2024-01-28',
    description: 'Lunch at Chipotle',
    categoryId: 'cat_001',
    status: 'CONFIRMED',
    aiConfidence: 0.95,
    paymentMethod: 'card',
    bankAccountId: 'ba_001',
    merchant: 'Chipotle',
  },
  {
    id: 'txn_002',
    amount: 15.00,
    currency: 'USD',
    transactionType: 'EXPENSE',
    transactionDate: '2024-01-28',
    description: 'Uber ride to office',
    categoryId: 'cat_002',
    status: 'CONFIRMED',
    aiConfidence: 0.98,
    paymentMethod: 'card', 
    bankAccountId: 'ba_001',
    merchant: 'Uber',
  },
  {
    id: 'txn_003',
    amount: 1200.00,
    currency: 'USD',
    transactionType: 'INCOME',
    transactionDate: '2024-01-27',
    description: 'Freelance Project Payment',
    categoryId: 'cat_007',
    status: 'CONFIRMED',
    aiConfidence: 1.0,
    paymentMethod: 'transfer',
    bankAccountId: 'ba_001',
    merchant: 'Client X',
  },
  {
    id: 'txn_004',
    amount: 89.99,
    currency: 'USD',
    transactionType: 'EXPENSE',
    transactionDate: '2024-01-26',
    description: 'Amazon Electronics',
    categoryId: 'cat_003',
    status: 'CONFIRMED',
    aiConfidence: 0.92,
    paymentMethod: 'card',
    bankAccountId: 'ba_002',
    merchant: 'Amazon',
  },
  {
    id: 'txn_005',
    amount: 14.99,
    currency: 'USD',
    transactionType: 'EXPENSE',
    transactionDate: '2024-01-25',
    description: 'Netflix Subscription',
    categoryId: 'cat_004',
    status: 'CONFIRMED',
    aiConfidence: 0.99,
    paymentMethod: 'card',
    bankAccountId: 'ba_001',
    merchant: 'Netflix',
  },
   {
    id: 'txn_006',
    amount: 125.50,
    currency: 'USD',
    transactionType: 'EXPENSE',
    transactionDate: '2024-01-29',
    description: 'Grocery shopping at Whole Foods',
    categoryId: 'cat_001',
    status: 'PENDING',
    aiConfidence: 0.85,
    paymentMethod: 'card',
    bankAccountId: 'ba_001',
    merchant: 'Whole Foods',
  },
  {
    id: 'txn_007',
    amount: 45.00,
    currency: 'USD',
    transactionType: 'EXPENSE',
    transactionDate: '2024-01-29',
    description: 'Gas station fill-up',
    categoryId: 'cat_002',
    status: 'CONFIRMED',
    aiConfidence: 0.96,
    paymentMethod: 'card',
    bankAccountId: 'ba_001',
    merchant: 'Shell',
  },
  {
    id: 'txn_008',
    amount: 1500.00,
    currency: 'USD',
    transactionType: 'EXPENSE',
    transactionDate: '2024-01-01',
    description: 'January Rent',
    categoryId: 'cat_010',
    status: 'CONFIRMED',
    aiConfidence: 1.0,
    paymentMethod: 'transfer',
    bankAccountId: 'ba_001',
    merchant: 'Landlord',
  }
]

export const sampleReceipts = [
  {
    id: 'rcp_001',
    fileName: 'whole_foods_receipt.jpg',
    uploadDate: '2024-01-29T10:30:00Z',
    status: 'PROCESSED',
    transactionCount: 8,
    processedCount: 6,
    documentType: 'Receipt',
    totalAmount: 345.50,
    previewUrl: '/placeholder-receipt.png' // We would normally use a real URL
  },
  {
    id: 'rcp_002',
    fileName: 'uber_jan_28.pdf',
    uploadDate: '2024-01-28T08:15:00Z',
    status: 'PROCESSED',
    transactionCount: 1,
    processedCount: 1,
    documentType: 'Invoice',
    totalAmount: 15.00,
    previewUrl: '/placeholder-receipt.png'
  },
  {
    id: 'rcp_003',
    fileName: 'bank_statement_jan.pdf',
    uploadDate: '2024-01-27T14:20:00Z',
    status: 'PENDING',
    transactionCount: 0,
    processedCount: 0,
    documentType: 'Bank Statement',
    totalAmount: 0,
    previewUrl: '/placeholder-receipt.png'
  }
]
